-- Datos iniciales de catálogos. Este archivo puede ejecutarse varias veces.

insert into public.platforms (family, name)
values
  ('pc', 'PC'),
  ('mobile', 'iOS'),
  ('mobile', 'Android'),
  ('xbox', 'Xbox One'),
  ('xbox', 'Xbox Series S|X'),
  ('playstation', 'PlayStation 4'),
  ('playstation', 'PlayStation 5'),
  ('nintendo', 'Nintendo Switch'),
  ('nintendo', 'Nintendo Switch 2')
on conflict (name) do nothing;

insert into public.subscriptions (name, tier, kind)
values
  ('Xbox Game Pass', 'Core', 'subscription'),
  ('Xbox Game Pass', 'Standard', 'subscription'),
  ('Xbox Game Pass', 'Ultimate', 'subscription'),
  ('PlayStation Plus', 'Essential', 'subscription'),
  ('PlayStation Plus', 'Extra', 'subscription'),
  ('PlayStation Plus', 'Premium', 'subscription'),
  ('Nintendo Switch Online', 'Base', 'subscription'),
  ('Nintendo Switch Online', '+ Expansion Pack', 'subscription'),
  ('EA Play', null, 'subscription'),
  ('Ubisoft+', null, 'subscription'),
  ('Apple Arcade', null, 'subscription'),
  ('Google Play Pass', null, 'subscription'),
  ('Amazon Luna', null, 'cloud'),
  ('GeForce NOW', null, 'cloud'),
  ('Xbox Cloud Gaming', null, 'cloud')
on conflict (name, tier) do nothing;

insert into public.genres (name)
values
  ('Acción'),
  ('Aventura'),
  ('RPG'),
  ('Shooter'),
  ('Estrategia'),
  ('Deportes'),
  ('Carreras'),
  ('Puzzle'),
  ('Plataformas'),
  ('Lucha'),
  ('Terror'),
  ('Simulación'),
  ('Cooperativo'),
  ('Battle Royale'),
  ('Indie'),
  ('Sandbox')
on conflict (name) do nothing;

insert into public.games (title, cover_url, metadata)
values
  ('Fortnite', null, '{}'::jsonb),
  ('Minecraft', null, '{}'::jsonb),
  ('Roblox', null, '{}'::jsonb),
  ('Among Us', null, '{}'::jsonb),
  ('Rocket League', null, '{}'::jsonb),
  ('Fall Guys', null, '{}'::jsonb),
  ('Apex Legends', null, '{}'::jsonb),
  ('Call of Duty: Warzone', null, '{}'::jsonb),
  ('Overwatch 2', null, '{}'::jsonb),
  ('VALORANT', null, '{}'::jsonb),
  ('League of Legends', null, '{}'::jsonb),
  ('Dota 2', null, '{}'::jsonb),
  ('Counter-Strike 2', null, '{}'::jsonb),
  ('PUBG: BATTLEGROUNDS', null, '{}'::jsonb),
  ('Halo Infinite', null, '{}'::jsonb),
  ('Forza Horizon 5', null, '{}'::jsonb),
  ('Sea of Thieves', null, '{}'::jsonb),
  ('Grounded', null, '{}'::jsonb),
  ('Minecraft Dungeons', null, '{}'::jsonb),
  ('It Takes Two', null, '{}'::jsonb),
  ('A Way Out', null, '{}'::jsonb),
  ('EA Sports FC 25', null, '{}'::jsonb),
  ('Mario Kart 8 Deluxe', null, '{}'::jsonb),
  ('Super Smash Bros. Ultimate', null, '{}'::jsonb),
  ('Splatoon 3', null, '{}'::jsonb),
  ('Mario Party Superstars', null, '{}'::jsonb),
  ('Animal Crossing: New Horizons', null, '{}'::jsonb),
  ('Pokémon Scarlet', null, '{}'::jsonb),
  ('Pokémon Violet', null, '{}'::jsonb),
  ('Nintendo Switch Sports', null, '{}'::jsonb),
  ('Mario Kart World', null, '{}'::jsonb),
  ('Helldivers 2', null, '{}'::jsonb),
  ('Baldur''s Gate 3', null, '{}'::jsonb),
  ('Diablo IV', null, '{}'::jsonb),
  ('Elden Ring', null, '{}'::jsonb),
  ('Monster Hunter Rise', null, '{}'::jsonb),
  ('Monster Hunter Wilds', null, '{}'::jsonb),
  ('Terraria', null, '{}'::jsonb),
  ('Stardew Valley', null, '{}'::jsonb),
  ('Don''t Starve Together', null, '{}'::jsonb),
  ('Street Fighter 6', null, '{}'::jsonb),
  ('Tekken 8', null, '{}'::jsonb),
  ('Mortal Kombat 1', null, '{}'::jsonb),
  ('Guilty Gear -Strive-', null, '{}'::jsonb),
  ('Trackmania', null, '{}'::jsonb),
  ('The Crew Motorfest', null, '{}'::jsonb),
  ('Need for Speed Unbound', null, '{}'::jsonb),
  ('Human: Fall Flat', null, '{}'::jsonb),
  ('Overcooked! 2', null, '{}'::jsonb),
  ('Portal 2', null, '{}'::jsonb),
  ('PAYDAY 3', null, '{}'::jsonb),
  ('Tom Clancy''s Rainbow Six Siege', null, '{}'::jsonb),
  ('Dead by Daylight', null, '{}'::jsonb),
  ('Phasmophobia', null, '{}'::jsonb),
  ('Lethal Company', null, '{}'::jsonb),
  ('Garry''s Mod', null, '{}'::jsonb)
on conflict (title) do nothing;

with seed(title, genre) as (
  values
    ('Fortnite', 'Shooter'),
    ('Fortnite', 'Battle Royale'),
    ('Minecraft', 'Aventura'),
    ('Minecraft', 'Cooperativo'),
    ('Minecraft', 'Sandbox'),
    ('Roblox', 'Aventura'),
    ('Roblox', 'Cooperativo'),
    ('Roblox', 'Sandbox'),
    ('Among Us', 'Cooperativo'),
    ('Among Us', 'Indie'),
    ('Rocket League', 'Deportes'),
    ('Rocket League', 'Carreras'),
    ('Fall Guys', 'Plataformas'),
    ('Fall Guys', 'Battle Royale'),
    ('Apex Legends', 'Shooter'),
    ('Apex Legends', 'Battle Royale'),
    ('Call of Duty: Warzone', 'Shooter'),
    ('Call of Duty: Warzone', 'Battle Royale'),
    ('Overwatch 2', 'Shooter'),
    ('VALORANT', 'Shooter'),
    ('League of Legends', 'Acción'),
    ('League of Legends', 'Estrategia'),
    ('Dota 2', 'Estrategia'),
    ('Counter-Strike 2', 'Shooter'),
    ('PUBG: BATTLEGROUNDS', 'Shooter'),
    ('PUBG: BATTLEGROUNDS', 'Battle Royale'),
    ('Halo Infinite', 'Shooter'),
    ('Forza Horizon 5', 'Carreras'),
    ('Sea of Thieves', 'Aventura'),
    ('Sea of Thieves', 'Cooperativo'),
    ('Grounded', 'Aventura'),
    ('Grounded', 'Cooperativo'),
    ('Minecraft Dungeons', 'Acción'),
    ('Minecraft Dungeons', 'RPG'),
    ('Minecraft Dungeons', 'Cooperativo'),
    ('It Takes Two', 'Aventura'),
    ('It Takes Two', 'Cooperativo'),
    ('A Way Out', 'Aventura'),
    ('A Way Out', 'Cooperativo'),
    ('EA Sports FC 25', 'Deportes'),
    ('Mario Kart 8 Deluxe', 'Carreras'),
    ('Super Smash Bros. Ultimate', 'Lucha'),
    ('Splatoon 3', 'Shooter'),
    ('Mario Party Superstars', 'Cooperativo'),
    ('Animal Crossing: New Horizons', 'Simulación'),
    ('Animal Crossing: New Horizons', 'Sandbox'),
    ('Pokémon Scarlet', 'RPG'),
    ('Pokémon Scarlet', 'Aventura'),
    ('Pokémon Violet', 'RPG'),
    ('Pokémon Violet', 'Aventura'),
    ('Nintendo Switch Sports', 'Deportes'),
    ('Mario Kart World', 'Carreras'),
    ('Helldivers 2', 'Shooter'),
    ('Helldivers 2', 'Cooperativo'),
    ('Baldur''s Gate 3', 'RPG'),
    ('Baldur''s Gate 3', 'Cooperativo'),
    ('Diablo IV', 'Acción'),
    ('Diablo IV', 'RPG'),
    ('Diablo IV', 'Cooperativo'),
    ('Elden Ring', 'Acción'),
    ('Elden Ring', 'RPG'),
    ('Monster Hunter Rise', 'Acción'),
    ('Monster Hunter Rise', 'RPG'),
    ('Monster Hunter Rise', 'Cooperativo'),
    ('Monster Hunter Wilds', 'Acción'),
    ('Monster Hunter Wilds', 'RPG'),
    ('Monster Hunter Wilds', 'Cooperativo'),
    ('Terraria', 'Aventura'),
    ('Terraria', 'Cooperativo'),
    ('Terraria', 'Sandbox'),
    ('Stardew Valley', 'Simulación'),
    ('Stardew Valley', 'Cooperativo'),
    ('Stardew Valley', 'Indie'),
    ('Don''t Starve Together', 'Aventura'),
    ('Don''t Starve Together', 'Cooperativo'),
    ('Don''t Starve Together', 'Indie'),
    ('Street Fighter 6', 'Lucha'),
    ('Tekken 8', 'Lucha'),
    ('Mortal Kombat 1', 'Lucha'),
    ('Guilty Gear -Strive-', 'Lucha'),
    ('Trackmania', 'Carreras'),
    ('The Crew Motorfest', 'Carreras'),
    ('Need for Speed Unbound', 'Carreras'),
    ('Human: Fall Flat', 'Puzzle'),
    ('Human: Fall Flat', 'Plataformas'),
    ('Human: Fall Flat', 'Cooperativo'),
    ('Overcooked! 2', 'Puzzle'),
    ('Overcooked! 2', 'Cooperativo'),
    ('Portal 2', 'Puzzle'),
    ('Portal 2', 'Cooperativo'),
    ('PAYDAY 3', 'Shooter'),
    ('PAYDAY 3', 'Cooperativo'),
    ('Tom Clancy''s Rainbow Six Siege', 'Shooter'),
    ('Dead by Daylight', 'Terror'),
    ('Dead by Daylight', 'Cooperativo'),
    ('Phasmophobia', 'Terror'),
    ('Phasmophobia', 'Cooperativo'),
    ('Lethal Company', 'Terror'),
    ('Lethal Company', 'Cooperativo'),
    ('Lethal Company', 'Indie'),
    ('Garry''s Mod', 'Sandbox'),
    ('Garry''s Mod', 'Cooperativo')
)
insert into public.game_genres (game_id, genre_id)
select g.id, r.id
from seed
join public.games g on g.title = seed.title
join public.genres r on r.name = seed.genre
on conflict (game_id, genre_id) do nothing;

with seed(title, platform) as (
  values
    ('Fortnite', 'PC'),
    ('Fortnite', 'Android'),
    ('Fortnite', 'Xbox One'),
    ('Fortnite', 'Xbox Series S|X'),
    ('Fortnite', 'PlayStation 4'),
    ('Fortnite', 'PlayStation 5'),
    ('Fortnite', 'Nintendo Switch'),
    ('Fortnite', 'Nintendo Switch 2'),
    ('Minecraft', 'PC'),
    ('Minecraft', 'iOS'),
    ('Minecraft', 'Android'),
    ('Minecraft', 'Xbox One'),
    ('Minecraft', 'Xbox Series S|X'),
    ('Minecraft', 'PlayStation 4'),
    ('Minecraft', 'PlayStation 5'),
    ('Minecraft', 'Nintendo Switch'),
    ('Roblox', 'PC'),
    ('Roblox', 'iOS'),
    ('Roblox', 'Android'),
    ('Roblox', 'Xbox One'),
    ('Roblox', 'Xbox Series S|X'),
    ('Roblox', 'PlayStation 4'),
    ('Roblox', 'PlayStation 5'),
    ('Among Us', 'PC'),
    ('Among Us', 'iOS'),
    ('Among Us', 'Android'),
    ('Among Us', 'Xbox One'),
    ('Among Us', 'Xbox Series S|X'),
    ('Among Us', 'PlayStation 4'),
    ('Among Us', 'PlayStation 5'),
    ('Among Us', 'Nintendo Switch'),
    ('Rocket League', 'PC'),
    ('Rocket League', 'Xbox One'),
    ('Rocket League', 'Xbox Series S|X'),
    ('Rocket League', 'PlayStation 4'),
    ('Rocket League', 'PlayStation 5'),
    ('Rocket League', 'Nintendo Switch'),
    ('Fall Guys', 'PC'),
    ('Fall Guys', 'Xbox One'),
    ('Fall Guys', 'Xbox Series S|X'),
    ('Fall Guys', 'PlayStation 4'),
    ('Fall Guys', 'PlayStation 5'),
    ('Fall Guys', 'Nintendo Switch'),
    ('Apex Legends', 'PC'),
    ('Apex Legends', 'Xbox One'),
    ('Apex Legends', 'Xbox Series S|X'),
    ('Apex Legends', 'PlayStation 4'),
    ('Apex Legends', 'PlayStation 5'),
    ('Apex Legends', 'Nintendo Switch'),
    ('Call of Duty: Warzone', 'PC'),
    ('Call of Duty: Warzone', 'Xbox One'),
    ('Call of Duty: Warzone', 'Xbox Series S|X'),
    ('Call of Duty: Warzone', 'PlayStation 4'),
    ('Call of Duty: Warzone', 'PlayStation 5'),
    ('Overwatch 2', 'PC'),
    ('Overwatch 2', 'Xbox One'),
    ('Overwatch 2', 'Xbox Series S|X'),
    ('Overwatch 2', 'PlayStation 4'),
    ('Overwatch 2', 'PlayStation 5'),
    ('Overwatch 2', 'Nintendo Switch'),
    ('VALORANT', 'PC'),
    ('VALORANT', 'Xbox Series S|X'),
    ('VALORANT', 'PlayStation 5'),
    ('League of Legends', 'PC'),
    ('Dota 2', 'PC'),
    ('Counter-Strike 2', 'PC'),
    ('PUBG: BATTLEGROUNDS', 'PC'),
    ('PUBG: BATTLEGROUNDS', 'Xbox One'),
    ('PUBG: BATTLEGROUNDS', 'Xbox Series S|X'),
    ('PUBG: BATTLEGROUNDS', 'PlayStation 4'),
    ('PUBG: BATTLEGROUNDS', 'PlayStation 5'),
    ('Halo Infinite', 'PC'),
    ('Halo Infinite', 'Xbox One'),
    ('Halo Infinite', 'Xbox Series S|X'),
    ('Forza Horizon 5', 'PC'),
    ('Forza Horizon 5', 'Xbox One'),
    ('Forza Horizon 5', 'Xbox Series S|X'),
    ('Sea of Thieves', 'PC'),
    ('Sea of Thieves', 'Xbox One'),
    ('Sea of Thieves', 'Xbox Series S|X'),
    ('Sea of Thieves', 'PlayStation 5'),
    ('Grounded', 'PC'),
    ('Grounded', 'Xbox One'),
    ('Grounded', 'Xbox Series S|X'),
    ('Grounded', 'PlayStation 4'),
    ('Grounded', 'PlayStation 5'),
    ('Grounded', 'Nintendo Switch'),
    ('Minecraft Dungeons', 'PC'),
    ('Minecraft Dungeons', 'Xbox One'),
    ('Minecraft Dungeons', 'Xbox Series S|X'),
    ('Minecraft Dungeons', 'PlayStation 4'),
    ('Minecraft Dungeons', 'PlayStation 5'),
    ('Minecraft Dungeons', 'Nintendo Switch'),
    ('It Takes Two', 'PC'),
    ('It Takes Two', 'Xbox One'),
    ('It Takes Two', 'Xbox Series S|X'),
    ('It Takes Two', 'PlayStation 4'),
    ('It Takes Two', 'PlayStation 5'),
    ('It Takes Two', 'Nintendo Switch'),
    ('A Way Out', 'PC'),
    ('A Way Out', 'Xbox One'),
    ('A Way Out', 'Xbox Series S|X'),
    ('A Way Out', 'PlayStation 4'),
    ('EA Sports FC 25', 'PC'),
    ('EA Sports FC 25', 'Xbox One'),
    ('EA Sports FC 25', 'Xbox Series S|X'),
    ('EA Sports FC 25', 'PlayStation 4'),
    ('EA Sports FC 25', 'PlayStation 5'),
    ('EA Sports FC 25', 'Nintendo Switch'),
    ('Mario Kart 8 Deluxe', 'Nintendo Switch'),
    ('Super Smash Bros. Ultimate', 'Nintendo Switch'),
    ('Splatoon 3', 'Nintendo Switch'),
    ('Mario Party Superstars', 'Nintendo Switch'),
    ('Animal Crossing: New Horizons', 'Nintendo Switch'),
    ('Pokémon Scarlet', 'Nintendo Switch'),
    ('Pokémon Violet', 'Nintendo Switch'),
    ('Nintendo Switch Sports', 'Nintendo Switch'),
    ('Mario Kart World', 'Nintendo Switch 2'),
    ('Helldivers 2', 'PC'),
    ('Helldivers 2', 'PlayStation 5'),
    ('Baldur''s Gate 3', 'PC'),
    ('Baldur''s Gate 3', 'Xbox Series S|X'),
    ('Baldur''s Gate 3', 'PlayStation 5'),
    ('Diablo IV', 'PC'),
    ('Diablo IV', 'Xbox One'),
    ('Diablo IV', 'Xbox Series S|X'),
    ('Diablo IV', 'PlayStation 4'),
    ('Diablo IV', 'PlayStation 5'),
    ('Elden Ring', 'PC'),
    ('Elden Ring', 'Xbox One'),
    ('Elden Ring', 'Xbox Series S|X'),
    ('Elden Ring', 'PlayStation 4'),
    ('Elden Ring', 'PlayStation 5'),
    ('Monster Hunter Rise', 'PC'),
    ('Monster Hunter Rise', 'Xbox One'),
    ('Monster Hunter Rise', 'Xbox Series S|X'),
    ('Monster Hunter Rise', 'PlayStation 4'),
    ('Monster Hunter Rise', 'PlayStation 5'),
    ('Monster Hunter Rise', 'Nintendo Switch'),
    ('Monster Hunter Wilds', 'PC'),
    ('Monster Hunter Wilds', 'Xbox Series S|X'),
    ('Monster Hunter Wilds', 'PlayStation 5'),
    ('Terraria', 'PC'),
    ('Terraria', 'iOS'),
    ('Terraria', 'Android'),
    ('Terraria', 'Xbox One'),
    ('Terraria', 'Xbox Series S|X'),
    ('Terraria', 'PlayStation 4'),
    ('Terraria', 'PlayStation 5'),
    ('Terraria', 'Nintendo Switch'),
    ('Stardew Valley', 'PC'),
    ('Stardew Valley', 'iOS'),
    ('Stardew Valley', 'Android'),
    ('Stardew Valley', 'Xbox One'),
    ('Stardew Valley', 'Xbox Series S|X'),
    ('Stardew Valley', 'PlayStation 4'),
    ('Stardew Valley', 'PlayStation 5'),
    ('Stardew Valley', 'Nintendo Switch'),
    ('Don''t Starve Together', 'PC'),
    ('Don''t Starve Together', 'Xbox One'),
    ('Don''t Starve Together', 'Xbox Series S|X'),
    ('Don''t Starve Together', 'PlayStation 4'),
    ('Don''t Starve Together', 'PlayStation 5'),
    ('Don''t Starve Together', 'Nintendo Switch'),
    ('Street Fighter 6', 'PC'),
    ('Street Fighter 6', 'Xbox Series S|X'),
    ('Street Fighter 6', 'PlayStation 4'),
    ('Street Fighter 6', 'PlayStation 5'),
    ('Tekken 8', 'PC'),
    ('Tekken 8', 'Xbox Series S|X'),
    ('Tekken 8', 'PlayStation 5'),
    ('Mortal Kombat 1', 'PC'),
    ('Mortal Kombat 1', 'Xbox Series S|X'),
    ('Mortal Kombat 1', 'PlayStation 5'),
    ('Mortal Kombat 1', 'Nintendo Switch'),
    ('Guilty Gear -Strive-', 'PC'),
    ('Guilty Gear -Strive-', 'Xbox One'),
    ('Guilty Gear -Strive-', 'Xbox Series S|X'),
    ('Guilty Gear -Strive-', 'PlayStation 4'),
    ('Guilty Gear -Strive-', 'PlayStation 5'),
    ('Trackmania', 'PC'),
    ('Trackmania', 'Xbox One'),
    ('Trackmania', 'Xbox Series S|X'),
    ('Trackmania', 'PlayStation 4'),
    ('Trackmania', 'PlayStation 5'),
    ('The Crew Motorfest', 'PC'),
    ('The Crew Motorfest', 'Xbox One'),
    ('The Crew Motorfest', 'Xbox Series S|X'),
    ('The Crew Motorfest', 'PlayStation 4'),
    ('The Crew Motorfest', 'PlayStation 5'),
    ('Need for Speed Unbound', 'PC'),
    ('Need for Speed Unbound', 'Xbox Series S|X'),
    ('Need for Speed Unbound', 'PlayStation 5'),
    ('Human: Fall Flat', 'PC'),
    ('Human: Fall Flat', 'iOS'),
    ('Human: Fall Flat', 'Android'),
    ('Human: Fall Flat', 'Xbox One'),
    ('Human: Fall Flat', 'Xbox Series S|X'),
    ('Human: Fall Flat', 'PlayStation 4'),
    ('Human: Fall Flat', 'PlayStation 5'),
    ('Human: Fall Flat', 'Nintendo Switch'),
    ('Overcooked! 2', 'PC'),
    ('Overcooked! 2', 'Xbox One'),
    ('Overcooked! 2', 'Xbox Series S|X'),
    ('Overcooked! 2', 'PlayStation 4'),
    ('Overcooked! 2', 'PlayStation 5'),
    ('Overcooked! 2', 'Nintendo Switch'),
    ('Portal 2', 'PC'),
    ('Portal 2', 'Xbox One'),
    ('PAYDAY 3', 'PC'),
    ('PAYDAY 3', 'Xbox Series S|X'),
    ('PAYDAY 3', 'PlayStation 5'),
    ('Tom Clancy''s Rainbow Six Siege', 'PC'),
    ('Tom Clancy''s Rainbow Six Siege', 'Xbox One'),
    ('Tom Clancy''s Rainbow Six Siege', 'Xbox Series S|X'),
    ('Tom Clancy''s Rainbow Six Siege', 'PlayStation 4'),
    ('Tom Clancy''s Rainbow Six Siege', 'PlayStation 5'),
    ('Dead by Daylight', 'PC'),
    ('Dead by Daylight', 'Xbox One'),
    ('Dead by Daylight', 'Xbox Series S|X'),
    ('Dead by Daylight', 'PlayStation 4'),
    ('Dead by Daylight', 'PlayStation 5'),
    ('Dead by Daylight', 'Nintendo Switch'),
    ('Phasmophobia', 'PC'),
    ('Phasmophobia', 'Xbox Series S|X'),
    ('Phasmophobia', 'PlayStation 5'),
    ('Lethal Company', 'PC'),
    ('Garry''s Mod', 'PC')
)
insert into public.game_availability (game_id, platform_id, subscription_id)
select g.id, p.id, null
from seed
join public.games g on g.title = seed.title
join public.platforms p on p.name = seed.platform
on conflict (game_id, platform_id, subscription_id) do nothing;

with seed(title, subscription, tier) as (
  values
    ('Halo Infinite', 'Xbox Game Pass', 'Standard'),
    ('Halo Infinite', 'Xbox Game Pass', 'Ultimate'),
    ('Forza Horizon 5', 'Xbox Game Pass', 'Standard'),
    ('Forza Horizon 5', 'Xbox Game Pass', 'Ultimate'),
    ('Sea of Thieves', 'Xbox Game Pass', 'Standard'),
    ('Sea of Thieves', 'Xbox Game Pass', 'Ultimate'),
    ('Grounded', 'Xbox Game Pass', 'Standard'),
    ('Grounded', 'Xbox Game Pass', 'Ultimate'),
    ('Minecraft Dungeons', 'Xbox Game Pass', 'Standard'),
    ('Minecraft Dungeons', 'Xbox Game Pass', 'Ultimate'),
    ('It Takes Two', 'EA Play', null),
    ('A Way Out', 'EA Play', null),
    ('Diablo IV', 'Xbox Game Pass', 'Standard'),
    ('Diablo IV', 'Xbox Game Pass', 'Ultimate')
)
insert into public.game_availability (game_id, platform_id, subscription_id)
select g.id, null, s.id
from seed
join public.games g on g.title = seed.title
join public.subscriptions s
  on s.name = seed.subscription
 and s.tier is not distinct from seed.tier
on conflict (game_id, platform_id, subscription_id) do nothing;
